name: My cluster
on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'ECS Cluster Name'
        required: true
      service-name:
        description: 'ECS Service Name'
        required: true
#       ssm-parameter-name:
#         description: 'SSM Parameter Name'
#         required: true

jobs:
  stop_service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Check ECS service status
        id: ecs_status
        run: |
          status=$(aws ecs describe-services --cluster ${{ github.event.inputs.cluster-name }} --services ${{ github.event.inputs.service-name }} --query 'services[0].status')
          echo "Service_Status=$status" >> $GITHUB_ENV
          echo "Service status: $status"

      - name: Get running task count
        id: task_count
        run: |
          count=$(aws ecs describe-services --cluster ${{ github.event.inputs.cluster-name }} --services ${{ github.event.inputs.service-name }} --query 'services[0].runningCount')
          echo "TASK_COUNT=$count" >> $GITHUB_ENV
          echo "Running Task Count: $count"
          
      - name: Check running task count
        id: check_task_count
        run: |
          if [[ ${{ env.TASK_COUNT }} == "0" ]]; then
            echo "No running tasks. Stopping pipeline execution."
            echo "task_count_zero=true" >> $GITHUB_ENV
          else
            echo "There are running tasks. Continuing pipeline execution."
          fi
          
      - name: Create SSM parameter
        if: step.check_task_count.output.task_count_zero != 'true'
        run: |
          if [[ "${{ env.TASK_COUNT }}" != "0" ]]; then
          aws ssm put-parameter --name ${{ github.event.inputs.cluster-name }} --value ${{ env.TASK_COUNT }} --type String --overwrite
          else
          echo "Task count is 0. Skipping parameter creation."
          fi
          
#       - name: Stop running tasks
#         run: |
#           aws ecs update-service --cluster ${{ github.event.inputs.cluster-name }} --service ${{ github.event.inputs.service-name }} --desired-count 0
#           echo "Stopped running tasks"        

#       - name: Read count value from SSM parameter
#         id: read_ssm_parameter
#         run: |
#           count=$(aws ssm get-parameter --name ${{ github.event.inputs.cluster-name }} --query 'Parameter.Value' --output text)
#           echo "TASK_COUNT=$count" >> $GITHUB_ENV
#           echo "Read Task Count from SSM: $count"

#       - name: Start tasks
#         run: |
#           aws ecs update-service --cluster ${{ github.event.inputs.cluster-name }} --service ${{ github.event.inputs.service-name }} --desired-count ${{ env.TASK_COUNT }}
#           echo "Started










